/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LanguageIdIndexRouteImport } from './routes/$languageId/index'
import { Route as LanguageIdTableValidateRouteImport } from './routes/$languageId/table/validate'
import { Route as LanguageIdTableInferSchemaRouteImport } from './routes/$languageId/table/infer-schema'
import { Route as LanguageIdFileValidateRouteImport } from './routes/$languageId/file/validate'
import { Route as LanguageIdFileInferDialectRouteImport } from './routes/$languageId/file/infer-dialect'
import { Route as LanguageIdDatasetValidateRouteImport } from './routes/$languageId/dataset/validate'
import { Route as LanguageIdDatasetInferRouteImport } from './routes/$languageId/dataset/infer'
import { Route as LanguageIdDataValidateRouteImport } from './routes/$languageId/data/validate'
import { Route as LanguageIdDataInferSchemaRouteImport } from './routes/$languageId/data/infer-schema'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageIdIndexRoute = LanguageIdIndexRouteImport.update({
  id: '/$languageId/',
  path: '/$languageId/',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageIdTableValidateRoute = LanguageIdTableValidateRouteImport.update({
  id: '/$languageId/table/validate',
  path: '/$languageId/table/validate',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageIdTableInferSchemaRoute =
  LanguageIdTableInferSchemaRouteImport.update({
    id: '/$languageId/table/infer-schema',
    path: '/$languageId/table/infer-schema',
    getParentRoute: () => rootRouteImport,
  } as any)
const LanguageIdFileValidateRoute = LanguageIdFileValidateRouteImport.update({
  id: '/$languageId/file/validate',
  path: '/$languageId/file/validate',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageIdFileInferDialectRoute =
  LanguageIdFileInferDialectRouteImport.update({
    id: '/$languageId/file/infer-dialect',
    path: '/$languageId/file/infer-dialect',
    getParentRoute: () => rootRouteImport,
  } as any)
const LanguageIdDatasetValidateRoute =
  LanguageIdDatasetValidateRouteImport.update({
    id: '/$languageId/dataset/validate',
    path: '/$languageId/dataset/validate',
    getParentRoute: () => rootRouteImport,
  } as any)
const LanguageIdDatasetInferRoute = LanguageIdDatasetInferRouteImport.update({
  id: '/$languageId/dataset/infer',
  path: '/$languageId/dataset/infer',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageIdDataValidateRoute = LanguageIdDataValidateRouteImport.update({
  id: '/$languageId/data/validate',
  path: '/$languageId/data/validate',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageIdDataInferSchemaRoute =
  LanguageIdDataInferSchemaRouteImport.update({
    id: '/$languageId/data/infer-schema',
    path: '/$languageId/data/infer-schema',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$languageId/': typeof LanguageIdIndexRoute
  '/$languageId/data/infer-schema': typeof LanguageIdDataInferSchemaRoute
  '/$languageId/data/validate': typeof LanguageIdDataValidateRoute
  '/$languageId/dataset/infer': typeof LanguageIdDatasetInferRoute
  '/$languageId/dataset/validate': typeof LanguageIdDatasetValidateRoute
  '/$languageId/file/infer-dialect': typeof LanguageIdFileInferDialectRoute
  '/$languageId/file/validate': typeof LanguageIdFileValidateRoute
  '/$languageId/table/infer-schema': typeof LanguageIdTableInferSchemaRoute
  '/$languageId/table/validate': typeof LanguageIdTableValidateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$languageId': typeof LanguageIdIndexRoute
  '/$languageId/data/infer-schema': typeof LanguageIdDataInferSchemaRoute
  '/$languageId/data/validate': typeof LanguageIdDataValidateRoute
  '/$languageId/dataset/infer': typeof LanguageIdDatasetInferRoute
  '/$languageId/dataset/validate': typeof LanguageIdDatasetValidateRoute
  '/$languageId/file/infer-dialect': typeof LanguageIdFileInferDialectRoute
  '/$languageId/file/validate': typeof LanguageIdFileValidateRoute
  '/$languageId/table/infer-schema': typeof LanguageIdTableInferSchemaRoute
  '/$languageId/table/validate': typeof LanguageIdTableValidateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$languageId/': typeof LanguageIdIndexRoute
  '/$languageId/data/infer-schema': typeof LanguageIdDataInferSchemaRoute
  '/$languageId/data/validate': typeof LanguageIdDataValidateRoute
  '/$languageId/dataset/infer': typeof LanguageIdDatasetInferRoute
  '/$languageId/dataset/validate': typeof LanguageIdDatasetValidateRoute
  '/$languageId/file/infer-dialect': typeof LanguageIdFileInferDialectRoute
  '/$languageId/file/validate': typeof LanguageIdFileValidateRoute
  '/$languageId/table/infer-schema': typeof LanguageIdTableInferSchemaRoute
  '/$languageId/table/validate': typeof LanguageIdTableValidateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$languageId/'
    | '/$languageId/data/infer-schema'
    | '/$languageId/data/validate'
    | '/$languageId/dataset/infer'
    | '/$languageId/dataset/validate'
    | '/$languageId/file/infer-dialect'
    | '/$languageId/file/validate'
    | '/$languageId/table/infer-schema'
    | '/$languageId/table/validate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$languageId'
    | '/$languageId/data/infer-schema'
    | '/$languageId/data/validate'
    | '/$languageId/dataset/infer'
    | '/$languageId/dataset/validate'
    | '/$languageId/file/infer-dialect'
    | '/$languageId/file/validate'
    | '/$languageId/table/infer-schema'
    | '/$languageId/table/validate'
  id:
    | '__root__'
    | '/'
    | '/$languageId/'
    | '/$languageId/data/infer-schema'
    | '/$languageId/data/validate'
    | '/$languageId/dataset/infer'
    | '/$languageId/dataset/validate'
    | '/$languageId/file/infer-dialect'
    | '/$languageId/file/validate'
    | '/$languageId/table/infer-schema'
    | '/$languageId/table/validate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LanguageIdIndexRoute: typeof LanguageIdIndexRoute
  LanguageIdDataInferSchemaRoute: typeof LanguageIdDataInferSchemaRoute
  LanguageIdDataValidateRoute: typeof LanguageIdDataValidateRoute
  LanguageIdDatasetInferRoute: typeof LanguageIdDatasetInferRoute
  LanguageIdDatasetValidateRoute: typeof LanguageIdDatasetValidateRoute
  LanguageIdFileInferDialectRoute: typeof LanguageIdFileInferDialectRoute
  LanguageIdFileValidateRoute: typeof LanguageIdFileValidateRoute
  LanguageIdTableInferSchemaRoute: typeof LanguageIdTableInferSchemaRoute
  LanguageIdTableValidateRoute: typeof LanguageIdTableValidateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$languageId/': {
      id: '/$languageId/'
      path: '/$languageId'
      fullPath: '/$languageId/'
      preLoaderRoute: typeof LanguageIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$languageId/table/validate': {
      id: '/$languageId/table/validate'
      path: '/$languageId/table/validate'
      fullPath: '/$languageId/table/validate'
      preLoaderRoute: typeof LanguageIdTableValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$languageId/table/infer-schema': {
      id: '/$languageId/table/infer-schema'
      path: '/$languageId/table/infer-schema'
      fullPath: '/$languageId/table/infer-schema'
      preLoaderRoute: typeof LanguageIdTableInferSchemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$languageId/file/validate': {
      id: '/$languageId/file/validate'
      path: '/$languageId/file/validate'
      fullPath: '/$languageId/file/validate'
      preLoaderRoute: typeof LanguageIdFileValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$languageId/file/infer-dialect': {
      id: '/$languageId/file/infer-dialect'
      path: '/$languageId/file/infer-dialect'
      fullPath: '/$languageId/file/infer-dialect'
      preLoaderRoute: typeof LanguageIdFileInferDialectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$languageId/dataset/validate': {
      id: '/$languageId/dataset/validate'
      path: '/$languageId/dataset/validate'
      fullPath: '/$languageId/dataset/validate'
      preLoaderRoute: typeof LanguageIdDatasetValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$languageId/dataset/infer': {
      id: '/$languageId/dataset/infer'
      path: '/$languageId/dataset/infer'
      fullPath: '/$languageId/dataset/infer'
      preLoaderRoute: typeof LanguageIdDatasetInferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$languageId/data/validate': {
      id: '/$languageId/data/validate'
      path: '/$languageId/data/validate'
      fullPath: '/$languageId/data/validate'
      preLoaderRoute: typeof LanguageIdDataValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$languageId/data/infer-schema': {
      id: '/$languageId/data/infer-schema'
      path: '/$languageId/data/infer-schema'
      fullPath: '/$languageId/data/infer-schema'
      preLoaderRoute: typeof LanguageIdDataInferSchemaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LanguageIdIndexRoute: LanguageIdIndexRoute,
  LanguageIdDataInferSchemaRoute: LanguageIdDataInferSchemaRoute,
  LanguageIdDataValidateRoute: LanguageIdDataValidateRoute,
  LanguageIdDatasetInferRoute: LanguageIdDatasetInferRoute,
  LanguageIdDatasetValidateRoute: LanguageIdDatasetValidateRoute,
  LanguageIdFileInferDialectRoute: LanguageIdFileInferDialectRoute,
  LanguageIdFileValidateRoute: LanguageIdFileValidateRoute,
  LanguageIdTableInferSchemaRoute: LanguageIdTableInferSchemaRoute,
  LanguageIdTableValidateRoute: LanguageIdTableValidateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
