/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LanguageSlugChar125IndexRouteImport } from './routes/{-$languageSlug}/index'
import { Route as Char123LanguageSlugChar125TableValidateRouteImport } from './routes/{-$languageSlug}/table/validate'
import { Route as Char123LanguageSlugChar125TableInferSchemaRouteImport } from './routes/{-$languageSlug}/table/infer-schema'
import { Route as Char123LanguageSlugChar125FileValidateRouteImport } from './routes/{-$languageSlug}/file/validate'
import { Route as Char123LanguageSlugChar125FileInferDialectRouteImport } from './routes/{-$languageSlug}/file/infer-dialect'
import { Route as Char123LanguageSlugChar125DatasetValidateRouteImport } from './routes/{-$languageSlug}/dataset/validate'
import { Route as Char123LanguageSlugChar125DatasetInferRouteImport } from './routes/{-$languageSlug}/dataset/infer'
import { Route as Char123LanguageSlugChar125DataValidateRouteImport } from './routes/{-$languageSlug}/data/validate'
import { Route as Char123LanguageSlugChar125DataInferSchemaRouteImport } from './routes/{-$languageSlug}/data/infer-schema'

const Char123LanguageSlugChar125IndexRoute =
  Char123LanguageSlugChar125IndexRouteImport.update({
    id: '/{-$languageSlug}/',
    path: '/{-$languageSlug}/',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LanguageSlugChar125TableValidateRoute =
  Char123LanguageSlugChar125TableValidateRouteImport.update({
    id: '/{-$languageSlug}/table/validate',
    path: '/{-$languageSlug}/table/validate',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LanguageSlugChar125TableInferSchemaRoute =
  Char123LanguageSlugChar125TableInferSchemaRouteImport.update({
    id: '/{-$languageSlug}/table/infer-schema',
    path: '/{-$languageSlug}/table/infer-schema',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LanguageSlugChar125FileValidateRoute =
  Char123LanguageSlugChar125FileValidateRouteImport.update({
    id: '/{-$languageSlug}/file/validate',
    path: '/{-$languageSlug}/file/validate',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LanguageSlugChar125FileInferDialectRoute =
  Char123LanguageSlugChar125FileInferDialectRouteImport.update({
    id: '/{-$languageSlug}/file/infer-dialect',
    path: '/{-$languageSlug}/file/infer-dialect',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LanguageSlugChar125DatasetValidateRoute =
  Char123LanguageSlugChar125DatasetValidateRouteImport.update({
    id: '/{-$languageSlug}/dataset/validate',
    path: '/{-$languageSlug}/dataset/validate',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LanguageSlugChar125DatasetInferRoute =
  Char123LanguageSlugChar125DatasetInferRouteImport.update({
    id: '/{-$languageSlug}/dataset/infer',
    path: '/{-$languageSlug}/dataset/infer',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LanguageSlugChar125DataValidateRoute =
  Char123LanguageSlugChar125DataValidateRouteImport.update({
    id: '/{-$languageSlug}/data/validate',
    path: '/{-$languageSlug}/data/validate',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LanguageSlugChar125DataInferSchemaRoute =
  Char123LanguageSlugChar125DataInferSchemaRouteImport.update({
    id: '/{-$languageSlug}/data/infer-schema',
    path: '/{-$languageSlug}/data/infer-schema',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/{-$languageSlug}/': typeof Char123LanguageSlugChar125IndexRoute
  '/{-$languageSlug}/data/infer-schema': typeof Char123LanguageSlugChar125DataInferSchemaRoute
  '/{-$languageSlug}/data/validate': typeof Char123LanguageSlugChar125DataValidateRoute
  '/{-$languageSlug}/dataset/infer': typeof Char123LanguageSlugChar125DatasetInferRoute
  '/{-$languageSlug}/dataset/validate': typeof Char123LanguageSlugChar125DatasetValidateRoute
  '/{-$languageSlug}/file/infer-dialect': typeof Char123LanguageSlugChar125FileInferDialectRoute
  '/{-$languageSlug}/file/validate': typeof Char123LanguageSlugChar125FileValidateRoute
  '/{-$languageSlug}/table/infer-schema': typeof Char123LanguageSlugChar125TableInferSchemaRoute
  '/{-$languageSlug}/table/validate': typeof Char123LanguageSlugChar125TableValidateRoute
}
export interface FileRoutesByTo {
  '/{-$languageSlug}': typeof Char123LanguageSlugChar125IndexRoute
  '/{-$languageSlug}/data/infer-schema': typeof Char123LanguageSlugChar125DataInferSchemaRoute
  '/{-$languageSlug}/data/validate': typeof Char123LanguageSlugChar125DataValidateRoute
  '/{-$languageSlug}/dataset/infer': typeof Char123LanguageSlugChar125DatasetInferRoute
  '/{-$languageSlug}/dataset/validate': typeof Char123LanguageSlugChar125DatasetValidateRoute
  '/{-$languageSlug}/file/infer-dialect': typeof Char123LanguageSlugChar125FileInferDialectRoute
  '/{-$languageSlug}/file/validate': typeof Char123LanguageSlugChar125FileValidateRoute
  '/{-$languageSlug}/table/infer-schema': typeof Char123LanguageSlugChar125TableInferSchemaRoute
  '/{-$languageSlug}/table/validate': typeof Char123LanguageSlugChar125TableValidateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$languageSlug}/': typeof Char123LanguageSlugChar125IndexRoute
  '/{-$languageSlug}/data/infer-schema': typeof Char123LanguageSlugChar125DataInferSchemaRoute
  '/{-$languageSlug}/data/validate': typeof Char123LanguageSlugChar125DataValidateRoute
  '/{-$languageSlug}/dataset/infer': typeof Char123LanguageSlugChar125DatasetInferRoute
  '/{-$languageSlug}/dataset/validate': typeof Char123LanguageSlugChar125DatasetValidateRoute
  '/{-$languageSlug}/file/infer-dialect': typeof Char123LanguageSlugChar125FileInferDialectRoute
  '/{-$languageSlug}/file/validate': typeof Char123LanguageSlugChar125FileValidateRoute
  '/{-$languageSlug}/table/infer-schema': typeof Char123LanguageSlugChar125TableInferSchemaRoute
  '/{-$languageSlug}/table/validate': typeof Char123LanguageSlugChar125TableValidateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$languageSlug}/'
    | '/{-$languageSlug}/data/infer-schema'
    | '/{-$languageSlug}/data/validate'
    | '/{-$languageSlug}/dataset/infer'
    | '/{-$languageSlug}/dataset/validate'
    | '/{-$languageSlug}/file/infer-dialect'
    | '/{-$languageSlug}/file/validate'
    | '/{-$languageSlug}/table/infer-schema'
    | '/{-$languageSlug}/table/validate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/{-$languageSlug}'
    | '/{-$languageSlug}/data/infer-schema'
    | '/{-$languageSlug}/data/validate'
    | '/{-$languageSlug}/dataset/infer'
    | '/{-$languageSlug}/dataset/validate'
    | '/{-$languageSlug}/file/infer-dialect'
    | '/{-$languageSlug}/file/validate'
    | '/{-$languageSlug}/table/infer-schema'
    | '/{-$languageSlug}/table/validate'
  id:
    | '__root__'
    | '/{-$languageSlug}/'
    | '/{-$languageSlug}/data/infer-schema'
    | '/{-$languageSlug}/data/validate'
    | '/{-$languageSlug}/dataset/infer'
    | '/{-$languageSlug}/dataset/validate'
    | '/{-$languageSlug}/file/infer-dialect'
    | '/{-$languageSlug}/file/validate'
    | '/{-$languageSlug}/table/infer-schema'
    | '/{-$languageSlug}/table/validate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LanguageSlugChar125IndexRoute: typeof Char123LanguageSlugChar125IndexRoute
  Char123LanguageSlugChar125DataInferSchemaRoute: typeof Char123LanguageSlugChar125DataInferSchemaRoute
  Char123LanguageSlugChar125DataValidateRoute: typeof Char123LanguageSlugChar125DataValidateRoute
  Char123LanguageSlugChar125DatasetInferRoute: typeof Char123LanguageSlugChar125DatasetInferRoute
  Char123LanguageSlugChar125DatasetValidateRoute: typeof Char123LanguageSlugChar125DatasetValidateRoute
  Char123LanguageSlugChar125FileInferDialectRoute: typeof Char123LanguageSlugChar125FileInferDialectRoute
  Char123LanguageSlugChar125FileValidateRoute: typeof Char123LanguageSlugChar125FileValidateRoute
  Char123LanguageSlugChar125TableInferSchemaRoute: typeof Char123LanguageSlugChar125TableInferSchemaRoute
  Char123LanguageSlugChar125TableValidateRoute: typeof Char123LanguageSlugChar125TableValidateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$languageSlug}/': {
      id: '/{-$languageSlug}/'
      path: '/{-$languageSlug}'
      fullPath: '/{-$languageSlug}/'
      preLoaderRoute: typeof Char123LanguageSlugChar125IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$languageSlug}/table/validate': {
      id: '/{-$languageSlug}/table/validate'
      path: '/{-$languageSlug}/table/validate'
      fullPath: '/{-$languageSlug}/table/validate'
      preLoaderRoute: typeof Char123LanguageSlugChar125TableValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$languageSlug}/table/infer-schema': {
      id: '/{-$languageSlug}/table/infer-schema'
      path: '/{-$languageSlug}/table/infer-schema'
      fullPath: '/{-$languageSlug}/table/infer-schema'
      preLoaderRoute: typeof Char123LanguageSlugChar125TableInferSchemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$languageSlug}/file/validate': {
      id: '/{-$languageSlug}/file/validate'
      path: '/{-$languageSlug}/file/validate'
      fullPath: '/{-$languageSlug}/file/validate'
      preLoaderRoute: typeof Char123LanguageSlugChar125FileValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$languageSlug}/file/infer-dialect': {
      id: '/{-$languageSlug}/file/infer-dialect'
      path: '/{-$languageSlug}/file/infer-dialect'
      fullPath: '/{-$languageSlug}/file/infer-dialect'
      preLoaderRoute: typeof Char123LanguageSlugChar125FileInferDialectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$languageSlug}/dataset/validate': {
      id: '/{-$languageSlug}/dataset/validate'
      path: '/{-$languageSlug}/dataset/validate'
      fullPath: '/{-$languageSlug}/dataset/validate'
      preLoaderRoute: typeof Char123LanguageSlugChar125DatasetValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$languageSlug}/dataset/infer': {
      id: '/{-$languageSlug}/dataset/infer'
      path: '/{-$languageSlug}/dataset/infer'
      fullPath: '/{-$languageSlug}/dataset/infer'
      preLoaderRoute: typeof Char123LanguageSlugChar125DatasetInferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$languageSlug}/data/validate': {
      id: '/{-$languageSlug}/data/validate'
      path: '/{-$languageSlug}/data/validate'
      fullPath: '/{-$languageSlug}/data/validate'
      preLoaderRoute: typeof Char123LanguageSlugChar125DataValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$languageSlug}/data/infer-schema': {
      id: '/{-$languageSlug}/data/infer-schema'
      path: '/{-$languageSlug}/data/infer-schema'
      fullPath: '/{-$languageSlug}/data/infer-schema'
      preLoaderRoute: typeof Char123LanguageSlugChar125DataInferSchemaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  Char123LanguageSlugChar125IndexRoute: Char123LanguageSlugChar125IndexRoute,
  Char123LanguageSlugChar125DataInferSchemaRoute:
    Char123LanguageSlugChar125DataInferSchemaRoute,
  Char123LanguageSlugChar125DataValidateRoute:
    Char123LanguageSlugChar125DataValidateRoute,
  Char123LanguageSlugChar125DatasetInferRoute:
    Char123LanguageSlugChar125DatasetInferRoute,
  Char123LanguageSlugChar125DatasetValidateRoute:
    Char123LanguageSlugChar125DatasetValidateRoute,
  Char123LanguageSlugChar125FileInferDialectRoute:
    Char123LanguageSlugChar125FileInferDialectRoute,
  Char123LanguageSlugChar125FileValidateRoute:
    Char123LanguageSlugChar125FileValidateRoute,
  Char123LanguageSlugChar125TableInferSchemaRoute:
    Char123LanguageSlugChar125TableInferSchemaRoute,
  Char123LanguageSlugChar125TableValidateRoute:
    Char123LanguageSlugChar125TableValidateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
